-- MySQL Script generated by MySQL Workbench
-- 09/21/20 09:22:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numeroExt` VARCHAR(45) NOT NULL,
  `numeroInt` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `munAlc` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(5) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contacto` (
  `idContacto` INT NOT NULL AUTO_INCREMENT,
  `nombreContacto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idContacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `idAlumno` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `aPaterno` VARCHAR(45) NOT NULL,
  `aMaterno` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(2) NOT NULL,
  `idDireccion` INT NOT NULL,
  `idContacto` INT NOT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `idDireccion_idx` (`idDireccion` ASC),
  INDEX `idContacto_idx` (`idContacto` ASC),
  CONSTRAINT `idDireccion`
    FOREIGN KEY (`idDireccion`)
    REFERENCES `mydb`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idContacto`
    FOREIGN KEY (`idContacto`)
    REFERENCES `mydb`.`Contacto` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoTelefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoTelefono` (
  `idTipoTelefono` INT NOT NULL AUTO_INCREMENT,
  `tipoTelefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoTelefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(45) NOT NULL,
  `idTipoTelefono` INT NOT NULL,
  PRIMARY KEY (`idTelefono`),
  INDEX `idTipoTelefono_idx` (`idTipoTelefono` ASC),
  CONSTRAINT `idTipoTelefono`
    FOREIGN KEY (`idTipoTelefono`)
    REFERENCES `mydb`.`TipoTelefono` (`idTipoTelefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetalleTelefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DetalleTelefono` (
  `idDetalleTelefono` INT NOT NULL AUTO_INCREMENT,
  `idContacto` INT NOT NULL,
  `idTelefono` INT NOT NULL,
  PRIMARY KEY (`idDetalleTelefono`),
  INDEX `idContacto_idx` (`idContacto` ASC),
  INDEX `idTelefono_idx` (`idTelefono` ASC),
  CONSTRAINT `idContacto`
    FOREIGN KEY (`idContacto`)
    REFERENCES `mydb`.`Contacto` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTelefono`
    FOREIGN KEY (`idTelefono`)
    REFERENCES `mydb`.`Telefono` (`idTelefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
