package hibernate.examples.model;
// Generated 11 sep. 2020 12:22:57 by Hibernate Tools 5.0.6.Final

/**
 * Phone generated by hbm2java
 */
public class Phone implements java.io.Serializable {

	private Integer id;
	private String number;
	private Integer idDetails;
	private CatPhoneType catPhoneType;
	private Client client;

	public Phone() {
	}

	public Phone(String number, Integer idDetails, CatPhoneType catPhoneType) {
		this.number = number;
		this.idDetails = idDetails;
		this.catPhoneType = catPhoneType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Integer getIdDetails() {
		return this.idDetails;
	}

	public void setIdDetails(Integer idDetails) {
		this.idDetails = idDetails;
	}

	public CatPhoneType getCatPhoneType() {
		return catPhoneType;
	}

	public void setCatPhoneType(CatPhoneType catPhoneType) {
		this.catPhoneType = catPhoneType;
	}
	
	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

}
